# Generated by Django 2.1.2 on 2018-10-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_auto_20181018_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='n_commoent',
            new_name='n_comment',
        ),
    ]
