# Generated by Django 2.1.2 on 2018-10-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='servers_hot_dogs',
            new_name='serves_hot_dogs',
        ),
    ]
