# Generated by Django 2.1.2 on 2018-10-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_auto_20181008_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='age1',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='age2',
        ),
    ]
