# Generated by Django 2.1.2 on 2018-10-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20181012_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='is_admin',
            field=models.BooleanField(blank=True, verbose_name='관리자'),
        ),
    ]
