# Generated by Django 2.1.2 on 2018-10-18 05:57

from django.db import migrations
import django.db.models.manager
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_auto_20181012_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('proxy.user1', models.Model),
            managers=[
                ('items', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user1',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저목록'},
        ),
    ]
